---
- hosts: remote
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Transfer from Master to Remote
      copy:
        src: /master/path/to/file
        dest: /remote/path/to/file

    - name: Detecting Files in Directory
      shell:
        cmd: "ls -1tr /master/path/to/file | head --lines=-0"
      register: ls_cmd
      changed_when: ls_cmd.stdout_lines | length > 0
      delegate_to: localhost

    - name: Clearing Files in Directory
      when: ls_cmd.stdout_lines|length > 0
      file:
        path: /master/path/to/file/{{ item }}
        state: absent
      loop: "{{ ls_cmd.stdout_lines }}"
      loop_control:
        label: "/master/path/to/file/{{ item }}"
      delegate_to: localhost
