---
- hosts: remote
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Transfer from Master to Remote
      copy:
        src: /home/imain/Desktop/movies
        dest: /home/panda/Desktop/movies

    - name: Detecting Files in Directory
      shell:
        cmd: "ls -1tr /home/imain/Desktop/movies | head --lines=-0"
      register: ls_cmd
      changed_when: ls_cmd.stdout_lines | length > 0
      delegate_to: localhost

    - name: Clearing Files in Directory
      when: ls_cmd.stdout_lines|length > 0
      file:
        path: /home/imain/Desktop/movies/{{ item }}
        state: absent
      loop: "{{ ls_cmd.stdout_lines }}"
      loop_control:
        label: "/home/imain/Desktop/movies/{{ item }}"
      delegate_to: localhost
